// pages/index.tsx
import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import HomepageHeroBanner from '@/components/HomepageHeroBanner';
import Services from '@/components/Services';
import WhoWeAre from '@/components/WhoWeAre';
import AlwaysOnGuard from '@/components/AlwaysOnGuard';
import IndustriesWeServe from '@/components/IndustriesWeServe';
import OurLeadershipTeam from '@/components/OurLeadershipTeam';
import OurPartners from '@/components/OurPartners';
import Subscribe from '@/components/Subscribe';
import IsoSertification from '@/components/IsoSertification';
import SmallSubscribe from '@/components/SmallSubscribe';
import OurCustomers from '@/components/OurCustomers';

const Home = () => {
  return (
    <>
      <Head>
        <title>My Next.js Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="d-flex flex-column min-vh-100">
        <Header />
        <HomepageHeroBanner />
        <Services />
        <WhoWeAre />
        <AlwaysOnGuard />
        <IndustriesWeServe />
        <OurLeadershipTeam />
        <OurPartners />
        <Subscribe />
        <IsoSertification />
        <SmallSubscribe />
        <OurCustomers />
        <Footer />
      </div>
    </>
  );
};

export default Home;



